name: CI
on:
  push:
    branches:
        - gha
jobs:
  stubs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Stubs
        run: |
          ./scripts/build-stubs.sh
      - name: Persist Stubs
        uses: actions/upload-artifact@v2
        with:
          name: stubs
          path: ./stubs
      - name: Persist Boards
        uses: actions/upload-artifact@v2
        with:
          name: stubs
          path: ./boards

  build:
    needs:
      - stubs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest
        ]
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses:  actions/setup-node@v1
        with:
          node-version: 14.16
      - name: npm install
        run: |
          npm install
          npm run electron-rebuild
      - name: Download Stubs
        uses: actions/download-artifact@v2
        with:
          name: stubs
      - name: Download Boards
        uses: actions/download-artifact@v2
        with:
          name: boards
      - name: Package Extension
        run: ./node_modules/.bin/vsce package -o vscode-circuitpython.vsix
      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: vscode-circuitpython-dev-${github.sha}.vsix
          path: ./vscode-circuitpython.vsix
      # TODO: Publish to VSCE Marketplace
