name: CI
on:
  push:
    branches:
        - gha
jobs:
  stubs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Stubs
        run: ./scripts/build-stubs.sh
      - name: Persist Stubs
        uses: actions/upload-artifact@v2
        with:
          name: stubs
          path: ./stubs
      - name: Persist Boards
        uses: actions/upload-artifact@v2
        with:
          name: boards
          path: ./boards

  build:
    needs:
      - stubs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
            npm_config_arch: x64
          - os: windows-latest
            platform: win32
            arch: ia32
            npm_config_arch: ia32
          #- os: windows-latest
          #  platform: win32
          #  arch: arm64
          #  npm_config_arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: x64
            npm_config_arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            npm_config_arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: armhf
            npm_config_arch: arm
          - os: ubuntu-latest
            platform: alpine
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
            npm_config_arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses:  actions/setup-node@v2
        with:
          node-version: 14.16
      - name: npm install
        run: |
          npm install
          npm run electron-rebuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_arch: ${{ matrix.npm_config_arch }}
      - name: Download Stubs
        uses: actions/download-artifact@v2
        with:
          name: stubs
      - name: Download Boards
        uses: actions/download-artifact@v2
        with:
          name: boards
      - shell: pwsh
        run: echo "target=${{ matrix.platform }}-${{ matrix.arch }}" >> $env:GITHUB_ENV
      - name: Package Extension
        run: ./node_modules/.bin/vsce package --target ${{ env.target }} -o vscode-circuitpython.vsix
      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: vscode-circuitpython-dev-${{ env.target }}-${{github.sha}}.vsix
          path: ./vscode-circuitpython.vsix
      #- name: Publish to VSCE Marketplace
      #  if: ${{ github.ref == 'refs/heads/master' }}

